# Generated by Django 3.0.6 on 2020-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='Date and time of image capture')),
                ('filename', models.CharField(max_length=50, null=True, verbose_name='Image filename')),
            ],
        ),
    ]
