# Generated by Django 3.0.6 on 2020-05-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeasApp', '0001_initial'),
    ]

    migrations.CreateModel(
        name='Timelapse',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('time_generated', models.DateTimeField(null=True, verbose_name='Date of video generation')),
            ('filename', models.CharField(max_length=200, verbose_name='Timestamp filename')),
            ('fps', models.DateTimeField(verbose_name='video frames per second')),
            ('num_frames', models.IntegerField(verbose_name='Number of frames in video')),
        ],
    ),
